# Generated by Django 3.0.8 on 2020-08-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_event_resources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='date',
            new_name='url',
        ),
    ]
