# Generated by Django 3.0.8 on 2020-08-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200813_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resources',
            name='url',
            field=models.TextField(),
        ),
    ]
